### ISSUE TITLE
Concept Ids in navigation data

### ISSUE THREAD

**Issue by aintgoin2goa** [Financial-Times/origami-navigation-service#39]
Previously on next the concept id of each item was included in the navigation data (where one existed).  This means we are able to easily query data on items in the navigation.  2 examples of this are the most read items in the meganav and also on subpages of the life and arts section where we show the most read items of the parent rather than the current stream page.

Currently we are having to maintain a hard-coded list mapping ids to urls and having this data with navigation would make it easier.

**Comment by JakeChampion** [comment]
Can this be solved with the Vanity tools that Next have created? Looking up a vanity to find out what the canonical source actually is named? cc @TheoLeanse as he owns the [next-url-management-api](https://github.com/Financial-Times/next-url-management-api)

**Comment by aintgoin2goa** [comment]
Yes, this is technically feasible, but it's an awful lot more work than just having the data with the navigation stuff where it has always been before.  It will potentially add more calls for each request or some kind of massive download of the whole vanity api data on startup - neither is ideal.

Having the ids in the navigation data, as well as being just generally useful, anchor the data to something tangible - both url and label are subject to change.  Without ids people will start writing code like `if(res.url === '/world')` which will break if someone changes that url to `/world-news` or whatever.

I feel a bit like I'm asking you to unlock a door and you're telling me to climb through the window instead.

**Comment by alicebartlett** [comment]
When we had a meeting with mus about this back when we built the v2 of the navigation service he said that a pain point for him was the (numeric) id sometimes changed resulting in it disappearing from the navigation without anybody noticing (this happened for the gold stream page for example).
Since Mus is only in charge of the vanity urls and not the corresponding section ids we've pushed the calculating the id outside of the scope of this tool to be the responsibility of developers further down the road.

What we've done here is optimised the experience for the people who maintain the navigation data (editorial) over that of the developers who use it.

If you're reading this and really want us to add ids back in, please comment on this issue and we can revisit.
